### ISSUE TITLE
cf部署失败 Output directory "dist" not found

### ISSUE THREAD

**Issue by xingyu42** [Clansty/chatrecord-viewer#3]
[chatrecord-viewer.5cff5fc0-9cb1-42dd-a8ba-b8edae5ad6cc.log](https://github.com/clansty/chatrecord-viewer/files/14513435/chatrecord-viewer.5cff5fc0-9cb1-42dd-a8ba-b8edae5ad6cc.log)
![image](https://github.com/clansty/chatrecord-viewer/assets/52421598/17f32ba4-3fa6-4b17-a167-4c727e736940)

**Comment by xingyu42** [comment]
![image](https://github.com/clansty/chatrecord-viewer/assets/52421598/fc45d286-98c1-4be1-9c3f-0def0644fd90)

**Comment by xingyu42** [comment]
切换到main分支部署好了

**Comment by DreamLight1337** [comment]
其实把构建指令改成“mkdir dist && pnpm build”就行
